--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LadySara48/CustomPanels
build-by-default: true
branches:
- stable
projects:
  CustomPanels:
    path: ""
    lint:
      phpstan: false
...
