name: CustomPanels
main: hearlov\custompanels\CustomPanels
author: Hearlov
description: "Custom YAML Inventory Panels"
version: 1.0
api: 5.0.0
depend:
 - InvMenu
softdepend:
 - EconomyAPI
 - BedrockEconomy
permissions:
  custompanels.openpanels:
    default: true
  custompanels.settings:
    default: op
