name: CustomPanels
main: hearlov\custompanels\CustomPanels
author: Hearlov
description: "Custom YAML Panels in Inventory. This plugin in BETA. (Performance Update COOMING SOON)"
version: 1.2.54-beta
api: 5.0.0
softdepend:
  - EconomyAPI
  - BedrockEconomy
permissions:
  custompanels.openpanels:
    default: true
  custompanels.settings:
    default: op
