name: CustomPanels
main: hearlov\custompanels\CustomPanels
author: Hearlov
description: "Custom YAML Inventory Panels this BETA"
version: 1.02-BETA
api: 5.0.0
depend:
  - DEVirion
softdepend:
  - EconomyAPI
  - BedrockEconomy
permissions:
  custompanels.openpanels:
    default: true
  custompanels.settings:
    default: op